image:
  - Visual Studio 2015
  - Ubuntu

branches:
  only:
    - master
    
install:
  - cmd: set QTDIR=C:\Qt\5.13\mingw73_32
  - cmd: set QT_TOOLS_DIR=C:\Qt\Tools\mingw730_32\ 
  - cmd: set PATH=%QTDIR%\bin;C:\Qt\Tools\mingw730_32\bin;%PATH%
  - sh: PATH=$HOME/Qt/5.14.2/gcc_64/bin:$PATH
  - qmake -v

build_script:
  - cd ShortStringTests
  - qmake "CONFIG+=debug"
  - sh: make check
  - sh: ls
  - sh: ls ../
  # On linux everything is built in the current dir
  - sh: gcov -r *.o
  - sh: bash <(curl -s https://codecov.io/bash)
  - cmd: mingw32-make check
  # on windows everything is built in debug or release dir
  - cmd: gcov -r debug\*.o
  - cmd: dir
  - cmd: dir ..\




